### ISSUE TITLE
will ostd be available?

### ISSUE THREAD

**Issue by hunej** [andrewssobral/ostd#1]
I wonder if there is a possibility that some sample code of ostd released...

**Comment by andrewssobral** [comment]
Hi @hunej thank you for your interest in the OSTD.
Yes, the source code will be available in the next few days, I you let you updated about this.
Best regards

**Comment by hunej** [comment]
Thank you very much!

**Comment by andrewssobral** [comment]
Hi @hunej sorry for my long delayed response.
The source code is now available, please let me know if you have any questions/problems:
https://github.com/andrewssobral/ostd
Best regards
